// hits
export const HITS_REQUEST = 'HITS_REQUEST';
export const HITS_REQUEST_SUCCESS = 'HITS_REQUEST_SUCCESS';
export const HITS_REQUEST_ERROR = 'HITS_REQUEST_ERROR';

//categories
export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_REQUEST_SUCCESS = 'CATEGORIES_REQUEST_SUCCESS';
export const CATEGORIES_REQUEST_ERROR = 'CATEGORIES_REQUEST_ERROR';

//catalog
export const CATALOG_REQUEST = 'CATALOG_REQUEST';
export const CATALOG_REQUEST_SUCCESS = 'CATALOG_REQUEST_SUCCESS';
export const CATALOG_REQUEST_ERROR = 'CATALOG_REQUEST_ERROR';

//cart
export const CART_ADD = 'CART_ADD';
export const CART_DELETE = 'CART_DELETE';
export const CART_CLEAR = 'CART_CLEAR';
